### ISSUE TITLE
default page doesn't highlight which model is selected

### ISSUE THREAD

**Issue by JWolochow** [SalesforceEng/runway-browser#2]
Issue: main page doesn't indicate whether i'm currently in bananas correct or broken

Suggestion: Should be consistent with the design that you build for after selecting correct or broken (where that item is highlighted blue to tell me that's where I currently am)

Screenshot:
![not indicating correct vs broken bananas](https://cloud.githubusercontent.com/assets/6818418/15099446/0ad5161c-150a-11e6-9299-9f7e6af5ecb3.png)

**Comment by ongardie-sfdc** [comment]
thanks, I think this is fixed now
